version: 5.0.0.{build}
image: Visual Studio 2022

before_build:
 - cmd: nuget restore src\Cardknox.sln
 
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}-ci'
  version_prefix: '{version}'
  package_version: '{version}-ci'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
build:
  verbosity: minimal

artifacts:
  - path: '**\*.nupkg'
    name: NuGet

for:

-
 branches:
   only:
     - 5.0
 
 configuration: Debug

 deploy:
   provider: NuGet
   server: https://nuget.pkg.github.com/ahwm/index.json
   artifact: /.nupkg/
   username: ahwm
   api_key:
     secure: 2zg4Byo45yLTMf0CtNlevjj6of7lXX4J9apMdpGru6VyFj2AzU6+A7QuPztrP6LK

-
 configuration: Release

 deploy:
   provider: NuGet
   api_key:
     secure: W4MtI5Ecxi0JGJ6LyP0dAkcW5DNdThYSFZhPC6FSc2CRSUoWjzUSe+SdAe1Cd9BC
   skip_symbols: false
   artifact: /Cardknox.*\.*nupkg/
   on:
     APPVEYOR_REPO_TAG: true
