version: 1.0.{build}
image: Visual Studio 2022

before_build:
 - cmd: nuget restore src\Cardknox.sln
 
build:
  verbosity: minimal

artifacts:
  - path: '\src\Cardknox.NET\bin\Release\Cardknox.API.Wrapper*.*nupkg'
    name: NuGet

for:

-
 branches:
   only:
     - master
     
 configuration: Release

 deploy:
   provider: NuGet
   api_key:
     secure: FeVtUyt5E1Fa86ZoyUH/m8p98uqQ6S0/KIJiqV7I8QhCgzk7h9TVNFampkJvBHzX
   skip_symbols: false
   artifact: /Cardknox.*\.*nupkg/
   on:
     APPVEYOR_REPO_TAG: true

-
 branches:
   only:
     - 5.0
     
 configuration: Release

 deploy:
   provider: NuGet
   api_key:
     secure: FeVtUyt5E1Fa86ZoyUH/m8p98uqQ6S0/KIJiqV7I8QhCgzk7h9TVNFampkJvBHzX
   skip_symbols: false
   artifact: /Cardknox.*\.*nupkg/
   on:
     APPVEYOR_REPO_TAG: true
