using System;
using System.Collections.Generic;
using System.Text;

namespace CardknoxApi.Operations
{
    /// <summary>
    /// 
    /// </summary>
    public class OperationBase : Customer
    {
        /// <summary>
        /// 
        /// </summary>
        public string CardNum { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string CVV { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Exp { get; set; }
        /// <summary>
        /// Checking Account Routing number
        /// </summary>
        public string Routing { get; set; }
        /// <summary>
        /// Checking Account number
        /// </summary>
        public string Account { get; set; }
        /// <summary>
        /// The routing, account and check number data from the bottom of a check in MICR (Magnetic Ink Character Recognition) format, typically generated by a check scanner.
        /// </summary>
        public string MICR { get; set; }
        /// <summary>
        /// The Check number.
        /// </summary>
        public string CheckNum { get; set; }
        /// <summary>
        /// The front image of the check, in Base 64 encoded image format.
        /// </summary>
        public string CheckImageFront { get; set; }
        /// <summary>
        /// The back image of the check, in Base 64 encoded image format.
        /// </summary>
        public string CheckImageBack { get; set; }
        /// <summary>
        /// The DUK/PT key for PIN Debit and EBT transactions.The first 16 characters are the encrypted pin block, followed by the 6 character long Key Set Identifier (KSID). The remaining characters are the PIN Pad serial number and transaction counter.
        /// </summary>
        public string DUKPT { get; set; }
        /// <summary>
        /// The total amount of the transaction, inclusive of tax and tip if applicable. This the total amount of the transaction.
        /// </summary>
        public decimal? Amount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Token { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Street { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Zip { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MagStripe { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public bool CardPresent { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public decimal? Tax { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public decimal? Tip { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Invoice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string IP { get; set; }
    }
}
